### ISSUE TITLE
Where to delete the uploaded file

### ISSUE THREAD

**Issue by sundar85** [mlabrum/vsts-download-secure-file#10]
Hi, 

Where to delete the uploaded file in the Download Secure File task? I need to remove the existing file and upload the latest one. Currently, I changed the name of the file, but I should be able to remove the old one, as I don't want someone mistakenly using the old file.

Thanks,
Sundar.

**Comment by itsho** [comment]
As far as I can see - since it gets downloaded to **temp** folder, the "_Post Job Cleanup_" at the end of the build process - is deleting the file. 

So, you don't need to do it by yourself.

**Comment by sundar85** [comment]
No I wanted to delete the File itself from the Secure File, but I had it figured out and I have removed it and re-uploaded a new version of the file.
